services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - MONGODB_URI=${MONGODB_URI}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NEXT_PUBLIC_JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
