"use client"

import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import {AppRouterCacheProvider} from "@mui/material-nextjs/v15-appRouter"
import { Roboto } from 'next/font/google';
import {QueryClient, QueryClientProvider} from "@tanstack/react-query"

const queryClient = new QueryClient()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <QueryClientProvider client={queryClient}>
            <Header/>
              {children}
            <ToastContainer/>
          </QueryClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
