import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import SidebarLayout from "./components/SidebarLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header/>
          <SidebarLayout>
            {children}
          </SidebarLayout>
        <ToastContainer/>
      </body>
    </html>
  );
}
